# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b1751222477f0243a781d6d419f72d5e969dabcd678754bd1e90ba75c35efcb0cab35753116448114ac16aeb9bf8c601ddc57785022841acdaea80678f2f7d7

test:
  secret_key_base: fb8cf60fbfb10f1c28814130c1f57ad045dcb34be28493c60648d768b07cf1a88f4e17b60ddfaa11f87e259ce5e2bbfb0cb7d6641b182eac029c2e6aa1ceab44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
